angular.module("configHub.repository.key",["diff-match-patch"]).controller("KeyController",["$scope","$http","$stateParams","$httpParamSerializer","editorInit","$state","$rootScope",function(b,g,f,e,d,c,a){b.auditRefreshCnt=0;
d.setState("key");
b.repoName=f.name;
b.account=f.owner;
a.selectedTab=0;
b.mode="key";
b.key=f.key;
b.initialized=true;
d.initialize(b);
b.postKeyDeleteCallback=function(){b.auditRefreshCnt++
};
b.postKeySaveCallback=function(h,i){if(h){c.go("repo.key",{owner:b.account,name:b.repoName,key:i},{notify:true})
}else{b.auditRefreshCnt++
}};
b.postValueSaveCallback=function(){b.auditRefreshCnt++
};
b.postValueDeleteCallback=function(h){b.auditRefreshCnt++
}
}]);