angular.module("configHub.login",[]).controller("LoginController",["$http","$state","$scope","$httpParamSerializer",function(d,c,a,b){a.email;
a.password;
a.login=function(){d({method:"POST",url:"/rest/login",data:b({email:a.email,password:a.password}),headers:{"Content-Type":"application/x-www-form-urlencoded"}}).then(function(e){if(e.data.success){a.processLoginToken(e.data.token);
c.go("dashboard")
}else{a.message=e.data.message
}})
}
}]).controller("PassResetController",["$http","$state","$scope","$httpParamSerializer",function(d,c,a,b){a.accountEmail;
a.message="";
a.sent=false;
a.resetPassword=function(){d({method:"POST",url:"/rest/resetLoginPassword",data:b({email:a.accountEmail}),headers:{"Content-Type":"application/x-www-form-urlencoded"}}).then(function(e){if(e.data.success){a.message="";
a.sent=true
}else{a.message=e.data.message;
a.sent=false
}})
}
}]).controller("PassChangeController",["$http","$state","$scope","$httpParamSerializer","$stateParams",function(f,d,a,c,e){a.password="";
a.password2="";
a.message="";
a.disableBtns=false;
var b=e.t;
f({method:"POST",url:"/rest/validatePassChangeToken",data:c({t:b}),headers:{"Content-Type":"application/x-www-form-urlencoded"}}).then(function(g){if(!g.data.success){a.message=g.data.message;
a.disableBtns=true
}});
a.savePassword=function(){f({method:"POST",url:"/rest/updateLoginPassword",data:c({password:a.password,password2:a.password2,t:b}),headers:{"Content-Type":"application/x-www-form-urlencoded"}}).then(function(g){if(g.data.success){a.message="";
a.processLoginToken(g.data.token);
d.go("dashboard")
}else{a.message=g.data.message;
a.password="";
a.password2=""
}})
}
}]);